# Utiliser une image de serveur web simple (Nginx)
FROM nginx:alpine

# Copier le fichier HTML dans le dossier de l'application web par défaut de Nginx
COPY index.html /usr/share/nginx/html/

# Exposer le port 80
EXPOSE 80
